<?php

function mediacommons_managment_init() {
}

function mediacommons_managment_findById($identifier) {
  $query = 'SELECT entity_id AS nid FROM {field_data_field_identifier} WHERE field_identifier_value = :identifier';
  $result = db_query($query, array(':identifier' => $identifier));
  $record = $result->fetchObject();
  if ($record) {
    return $record->nid;
  }
  else {
    return false;
  }
}

function mediacommons_managment_projects() {
  $projects = &drupal_static(__FUNCTION__, array());
  return $projects;
}

function mediacommons_managment_default_content() {
  return json_decode(file_get_contents(dirname(__DIR__) . '/features/projects/nodes.json'));
}

function mediacommons_managment_import_default_projects() {
  drupal_flush_all_caches();
}
